### ISSUE TITLE
百度地图坐标偏移

### ISSUE THREAD

**Issue by PongChen** [luxiaoxun/MapDownloader#1]
请问下作者，加载百度地图后，wgs84坐标按百度偏移后加载到地图上依然位置不对，这是一个已知问题吗

**Comment by luxiaoxun** [comment]
代码里的实现就是百度坐标实现，但是我把百度的坐标放到地图上和百度官方的仍然对不上。
参考下这个实现：
https://gitee.com/adodo1/TilesDownloader
http://git.oschina.net/adodo1/TilesDownloader

**Comment by PongChen** [comment]
> 代码里的实现就是百度坐标实现，但是我把百度的坐标放到地图上和百度官方的仍然对不上。
> 参考下这个实现：
> https://gitee.com/adodo1/TilesDownloader
> http://git.oschina.net/adodo1/TilesDownloader

谢谢，完美解决了
