### ISSUE TITLE
使用百度地图数据源的问题

### ISSUE THREAD

**Issue by Denny0503** [luxiaoxun/MapDownloader#3]
请问在使用百度地图的情况下，设置位置坐标，需要手动转换坐标系为百度吗？
我现在测试，输入百度坐标系的经纬度，发现偏移严重。偏移了几公里
而把输入的百度坐标转为GCJ02坐标时，再切换为高德地图，这时候的位置是显示正确的。

**Comment by luxiaoxun** [comment]
代码里的实现就是百度坐标实现，但是我把百度的坐标放到地图上和百度官方的仍然对不上。
参考下这个实现：
https://gitee.com/adodo1/TilesDownloader
http://git.oschina.net/adodo1/TilesDownloader

**Comment by Denny0503** [comment]
ok，知道是怎么处理的了，谢谢！
