### ISSUE TITLE
多标记

### ISSUE THREAD

**Issue by aklegend** [luxiaoxun/MapDownloader#5]
我想在数据库的地图控件上显示多个标记。 您能否通过选择组合框显示我如何从数据库中执行此操作。

**Comment by luxiaoxun** [comment]
“数据库的地图控件”？不明白你的意思

**Comment by aklegend** [comment]
从数据库记录。 我的位置存储在Microsoft SQL数据库中。 我正在从数据库将位置加载到Datagridview中，但我想将加载的位置显示在GMap.Net Control上的datagridview中作为标记。 像用户一样，从组合框中选择区域名称，所有基于区域的位置都将加载到datagridview中。 我想当用户从组合框中选择区域时，所有标记都显示在Gmap.net地图控件/地图视图上。

**Comment by luxiaoxun** [comment]
这不就是一些组件之间的数据联动吗，写代码实现就行了
